DATA_PATH: 'data/'
LLM: 'mistral:latest'
EMBEDDINGS: 'sentence-transformers/all-mpnet-base-v2'
WEAVIATE_URL: 'http://localhost:8081'
INDEX_NAME: 'LLama'
CHUNK_SIZE: 1000
OLLAMA_BASE_URL: 'http://192.168.68.110:11434'